services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong!Passw0rd#2024"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    restart: unless-stopped
    depends_on:
      sqledge:
        condition: service_started
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Strong!Passw0rd#2024"
      ACCEPT_EULA: "Y"
      CONFIG_PATH: /ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    volumes:
      - ../.devcontainer/servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json:ro
