name: content-api

# This workflow is triggered on push to the 'content-web' directory of the  master branch of the repository
on:
  push:
    branches:
    - master
    paths:
    - 'content-api/**'

  # Configure workflow to also support triggering manually
  workflow_dispatch:

# Environment variables are defined so that they can be used throughout the job definitions.
env:
  imageRepository: 'content/api'
  dockerfilePath: './content-api'
  tag: '${{ github.run_id  }}'

# Jobs define the actions that take place when code is pushed to the master branch
jobs:

  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.dockerfilePath }}

    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Docker login
      run: |
        docker login ${{ vars.CONTAINERREGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
    
    - name: Build image
      run: |
        docker build -t ${{ vars.CONTAINERREGISTRY }}/${{ env.imageRepository }}:${{ env.tag }} .

    - name: Push container image
      run: |
        docker push ${{ vars.CONTAINERREGISTRY }}/${{ env.imageRepository }}:${{ env.tag }}
