name: content-api-deploy

# This workflow is triggered on push to the 'content-web' directory of the  master branch of the repository
on:
  # Configure workflow to also support triggering manually
  workflow_dispatch:
    inputs:
        tag:
            description: 'Content API image tag value'
            required: true
        environment:
            type: choice
            description: 'Target environment name'
            required: true
            options: 
            - PoC
            - dev
            - test

# Environment variables are defined so that they can be used throughout the job definitions.
env:
  resourceGroupName: 'ARG-BROWNBAG-${{ github.event.inputs.environment }}-NCH-01'
  imageRepository: 'content/api'
  healthCheckUrl: 'https://${{ vars.WEB_API_NAME }}.azurewebsites.net/version'

# Jobs define the actions that take place when code is pushed to the master branch
jobs:

  deploy-docker-image:
    name: Deploy Docker Image
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: "Login via Azure CLI"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: AZ WebApp Set
      run: |
        az webapp config container set \
            --resource-group ${{ env.resourceGroupName }} \
            --name ${{ vars.WEB_API_NAME }} \
            --docker-custom-image-name ${{ vars.CONTAINERREGISTRY }}.azurecr.io/${{ env.imageRepository }}:${{ github.event.inputs.tag }}

    - name: Check deployment
      if: success()
      id: 'checkDeployment'
      continue-on-error: true
      run: |
        url=${{ env.healthCheckUrl }}
        for i in $(seq 1 10)  
        do 
          result=$(curl -s $url | jq .version)
          result=$(echo $result | tr -d '"')
          
          if [[ "$result" = "${{ github.event.inputs.tag }}" ]]; then
            echo "Correct build number: $result."
            exit 0  
          fi
          sleep 10
        done
        echo "Wrong build number ($result)."
        # It failed a lot of time
        exit 1
